# Generated by Django 3.2.5 on 2023-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
