# Generated by Django 3.2.5 on 2023-07-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patientrecord_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Patient')], null=True),
        ),
    ]
